spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pahiramcar?createDatabaseIfNotExist=true
    username: root
    password: homecredit123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080
  forward-headers-strategy: framework

cloudinary:
  cloud-name: do8vzin4m
  api-key: 737733589814552
  api-secret: YV2Jb4AIrtGcEj1BaFIp1wTqY8U

